# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: customer
  tag: v1.0.0
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 300Mi

service:
  name: customer
  cloudantservicename: cloudant-service
  type: NodePort
  servicePort: 9080
  servicePortHttps: 9443

services:
base:
  enabled: false
  replicaCount: 1
  image:
    tag : v0.9.9
  weight: 100

jwt:
  id: myMpJwt
  uri: https://auth-service:9443/oidc/endpoint/OP/jwk
  issuer: https://auth-service:9443/oidc/endpoint/OP

cloudant:
  user: admin
  password: pass
  protocol: http
  host: localhost
  port: 8081
  database: customers
